version: '3.0'
services:
  nginx:
      container_name: "nginx"
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./server.key:/app/server.key
        - ./server.crt:/app/server.crt
      ports:
        - 8443:8443
      depends_on:
        - server
        - action
        - mongo
        - main
        - rabbit

  mongo:
    image: mongo
    container_name: tracker-store

  server:
    container_name: rasa-server
    env_file:
      - .env
    build:
      context: chatbot
    links:
      - action
      - mongo

  action:
    container_name: rasa-action-server
    env_file:
      - .env
    build: 
      context: actions
    volumes:
      - ./actions:/app/actions


  main:
    container_name: main
    env_file:
      - .env
    build : 
      context: flask-app
    volumes:
      - ./flask-app:/app/flask-app
    command: 
      gunicorn -w 2 --chdir /app/flask-app app:app -b :5000 --log-level debug --reload

  rabbit:
    restart: always
    image: "bitnami/rabbitmq:3.7.17"
    container_name: rabbit
    env_file:
      - .env
   

    

